# frozen_string_literal: true

require_relative 'test_helper'
require 'fileutils'
require 'json'
require 'yaml'

module SeamInitializerTestHelpers
  COMMAND = File.expand_path('../skills/shaka/scripts/shaka', __dir__)
  GENERATED_MARKER = 'Generated by shaka seam init.'

  def with_repository(&)
    Dir.mktmpdir('shaka-seam-init') do |root|
      FileUtils.mkdir_p(File.join(root, 'bin'))
      %w[setup validate].each do |name|
        path = File.join(root, 'bin', name)
        File.write(path, "#!/bin/sh\nexit 0\n")
        File.chmod(0o755, path)
      end
      yield root
    end
  end

  def init(root, setup_command: 'bin/setup', validate_command: 'bin/validate',
           test_command: 'bundle exec rake test')
    Open3.capture3(*init_arguments(root, setup_command:, validate_command:, test_command:))
  end

  def init_arguments(root, setup_command: 'bin/setup', validate_command: 'bin/validate',
                     test_command: 'bundle exec rake test')
    [COMMAND, 'seam', 'init', '--root', root, '--base-branch', 'main',
     '--setup-command', setup_command, '--validate-command', validate_command,
     '--test-command', test_command, '--review-policy', 'meaningful_changes',
     '--review-check', 'claude-review',
     '--required-check', 'validate', '--trusted-action', 'actions/checkout',
     '--trusted-action', 'ruby/setup-ruby']
  end

  def generated_files(root)
    ['.agents/agent-workflow.yml', '.agents/bin/setup', '.agents/bin/validate', '.agents/bin/test']
      .map { |path| File.join(root, path) }
  end

  def snapshot(root)
    generated_files(root).to_h { |path| [path, [File.read(path), File.stat(path).mode]] }
  end

  def assert_complete_seam(root, output)
    config = JSON.parse(output)
    assert_equal %w[main ask], [config.fetch('base_branch'), config.dig('merge', 'preference')]
    assert_equal ['validate'], config.dig('protection', 'required_checks')
    assert_equal %w[actions/checkout ruby/setup-ruby], config.fetch('trusted_actions')
    assert_includes File.read(File.join(root, '.agents/agent-workflow.yml')), GENERATED_MARKER
    generated_files(root).drop(1).each { |path| assert_generated_wrapper(path) }
  end

  def assert_generated_wrapper(path)
    assert File.executable?(path)
    assert_includes File.read(path), GENERATED_MARKER
  end

  def write_recorder(root)
    FileUtils.mkdir_p(File.join(root, 'bin'))
    File.write(File.join(root, 'bin/record.rb'), <<~RUBY)
      require 'json'
      File.write('arguments.json', JSON.generate(ARGV))
    RUBY
  end

  def assert_forwarded_arguments(root)
    runtime_argument = '; touch should-not-exist'
    command = File.join(root, '.agents/bin/test')
    _output, status = Open3.capture2e(command, 'space value', runtime_argument)
    recorded = JSON.parse(File.read(File.join(root, 'arguments.json')))
    assert status.success?
    assert_equal ['configured', 'space value', runtime_argument], recorded
    refute File.exist?(File.join(root, 'should-not-exist'))
  end

  def write_foreign_test_wrapper(root)
    FileUtils.mkdir_p(File.join(root, '.agents/bin'))
    path = File.join(root, '.agents/bin/test')
    File.write(path, "#!/bin/sh\necho repository-owned\n")
    path
  end

  def with_external_executable
    Dir.mktmpdir('shaka-seam-outside') do |outside|
      path = File.join(outside, 'setup')
      File.write(path, "#!/bin/sh\n")
      File.chmod(0o755, path)
      yield path
    end
  end

  def git!(root, *)
    output, status = Open3.capture2e('git', '-C', root, *)
    raise output unless status.success?
  end

  def prepare_detached_previous_checkout(root)
    git!(root, 'init', '--initial-branch', 'main')
    git!(root, 'add', '.')
    git!(root, '-c', 'user.name=Test', '-c', 'user.email=test@example.com', 'commit', '-m', 'initial')
    git!(root, 'switch', '--detach', 'HEAD')
    git!(root, 'switch', 'main')
  end
end

class SeamInitializerTest < Minitest::Test
  include SeamInitializerTestHelpers

  def test_init_creates_and_validates_a_complete_repository_seam
    with_repository do |root|
      output, error, status = init(root)

      assert status.success?, error
      assert_complete_seam(root, output)
    end
  end

  def test_generated_command_forwards_runtime_arguments_without_shell_interpretation
    with_repository do |root|
      write_recorder(root)
      _output, error, status = init(root, test_command: 'ruby bin/record.rb configured')
      assert status.success?, error
      assert_forwarded_arguments(root)
    end
  end

  def test_repeat_init_is_idempotent
    with_repository do |root|
      assert init(root).last.success?
      original = snapshot(root)

      output, error, status = init(root)

      assert status.success?, error
      assert JSON.parse(output)
      assert_equal original, snapshot(root)
    end
  end

  def test_refuses_a_generated_wrapper_with_changed_mode
    with_repository do |root|
      assert init(root).last.success?
      setup = File.join(root, '.agents/bin/setup')
      File.chmod(0o644, setup)

      _output, error, status = init(root)

      refute status.success?
      assert_includes error, 'Refusing existing destination: .agents/bin/setup'
      refute File.executable?(setup)
    end
  end

  def test_refuses_foreign_config_before_writing_any_wrapper
    with_repository do |root|
      FileUtils.mkdir_p(File.join(root, '.agents'))
      config_path = File.join(root, '.agents/agent-workflow.yml')
      File.write(config_path, "owner: repository\n")

      _output, error, status = init(root)

      refute status.success?
      assert_includes error, 'Refusing existing destination'
      assert_equal "owner: repository\n", File.read(config_path)
      refute File.exist?(File.join(root, '.agents/bin'))
    end
  end

  def test_refuses_foreign_wrapper_before_writing_config_or_siblings
    with_repository do |root|
      test_path = write_foreign_test_wrapper(root)

      _output, error, status = init(root)

      refute status.success?
      assert_includes error, 'Refusing existing destination'
      assert_equal "#!/bin/sh\necho repository-owned\n", File.read(test_path)
      untouched = %w[.agents/agent-workflow.yml .agents/bin/setup]
      refute(untouched.any? { |path| File.exist?(File.join(root, path)) })
    end
  end

  def test_rejects_shell_control_operators_before_writing
    with_repository do |root|
      _output, error, status = init(root, validate_command: 'bin/validate && publish')

      refute status.success?
      assert_includes error, 'must be a simple argv command'
      refute File.exist?(File.join(root, '.agents'))
    end
  end

  def test_rejects_a_missing_repository_executable_before_writing
    with_repository do |root|
      _output, error, status = init(root, setup_command: 'bin/missing')

      refute status.success?
      assert_includes error, 'setup command does not exist: bin/missing'
      refute File.exist?(File.join(root, '.agents'))
    end
  end

  def test_rejects_a_missing_plan_before_writing
    with_repository do |root|
      arguments = [*init_arguments(root), '--plan', 'docs/missing.md']
      _output, error, status = Open3.capture3(*arguments)

      refute status.success?
      assert_includes error, 'plan does not exist: docs/missing.md'
      refute File.exist?(File.join(root, '.agents'))
    end
  end
end

class SeamInitializerValidationTest < Minitest::Test
  include SeamInitializerTestHelpers

  def test_rejects_missing_required_policy_before_writing
    %w[--base-branch --review-policy --review-check --required-check].each do |flag|
      with_repository do |root|
        arguments = init_arguments(root)
        arguments.slice!(arguments.index(flag), 2)
        _output, error, status = Open3.capture3(*arguments)

        refute status.success?
        assert_includes error, 'is required'
        refute File.exist?(File.join(root, '.agents'))
      end
    end
  end

  def test_review_policy_none_omits_the_review_check
    with_repository do |root|
      arguments = init_arguments(root)
      arguments[arguments.index('meaningful_changes')] = 'none'
      arguments.slice!(arguments.index('--review-check'), 2)

      output, error, status = Open3.capture3(*arguments)

      assert status.success?, error
      assert_equal({ 'required' => 'none' }, JSON.parse(output).fetch('review'))
    end
  end

  def test_rejects_an_invalid_branch_before_writing
    with_repository do |root|
      _output, error, status = Open3.capture3(*init_arguments(root).tap { |args| args[args.index('main')] = '-bad' })
      refute status.success?
      assert_includes error, 'base branch must be a valid Git branch name'
      refute File.exist?(File.join(root, '.agents'))
    end
  end

  def test_rejects_branch_shorthand_that_resolves_to_a_detached_commit
    with_repository do |root|
      prepare_detached_previous_checkout(root)
      arguments = init_arguments(root)
      arguments[arguments.index('main')] = '@{-1}'

      _output, error, status = Open3.capture3(*arguments)

      refute status.success?
      assert_includes error, 'base branch must be an explicit branch name'
      refute File.exist?(File.join(root, '.agents'))
    end
  end

  def test_rejects_a_non_executable_command_before_writing
    with_repository do |root|
      File.write(File.join(root, 'bin/not-executable'), "#!/bin/sh\n")
      _output, error, status = init(root, setup_command: 'bin/not-executable')
      refute status.success?
      assert_includes error, 'setup command is not executable'
      refute File.exist?(File.join(root, '.agents'))
    end
  end

  def test_rejects_a_missing_path_command_before_writing
    with_repository do |root|
      _output, error, status = init(root, test_command: 'shaka-command-that-does-not-exist')

      refute status.success?
      assert_includes error, 'test command is not available on PATH'
      refute File.exist?(File.join(root, '.agents'))
    end
  end

  def test_rejects_an_invalid_merge_preference_before_writing
    with_repository do |root|
      _output, error, status = Open3.capture3(*init_arguments(root), '--merge-preference', 'sometimes')

      refute status.success?
      assert_includes error, 'invalid argument'
      refute File.exist?(File.join(root, '.agents'))
    end
  end

  def test_refuses_a_symlinked_agents_directory
    with_repository do |root|
      FileUtils.mkdir_p(File.join(root, 'elsewhere'))
      File.symlink(File.join(root, 'elsewhere'), File.join(root, '.agents'))

      _output, error, status = init(root)

      refute status.success?
      assert_includes error, 'Refusing unsafe directory: .agents'
      assert_empty Dir.children(File.join(root, 'elsewhere'))
    end
  end

  def test_refuses_a_command_symlink_that_escapes_the_repository
    with_external_executable do |target|
      with_repository do |root|
        File.symlink(target, File.join(root, 'bin/external-setup'))

        _output, error, status = init(root, setup_command: 'bin/external-setup')

        refute status.success?
        assert_includes error, 'setup command must resolve inside the repository'
        refute File.exist?(File.join(root, '.agents'))
      end
    end
  end
end
