# frozen_string_literal: true

require 'fileutils'
require 'json'
require 'open3'
require 'tmpdir'
require_relative '../../skills/shaka/lib/shaka/seam'

# Harmless version-one repository used by the layout upgrade tests.
module SeamUpgradeFixture
  COMMAND = File.expand_path('../../skills/shaka/scripts/shaka', __dir__)
  ROOT_LINE = 'root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)'

  def with_repository
    Dir.mktmpdir('shaka-upgrade-test') do |parent|
      root = File.join(parent, 'repo')
      install_fixture_files(root)
      commit_fixture(root)
      yield root, parent
    end
  end

  def install_fixture_files(root)
    FileUtils.mkdir_p(File.join(root, '.agents/bin'))
    FileUtils.mkdir_p(File.join(root, 'bin'))
    File.write(File.join(root, '.agents/agent-workflow.yml'), fixture_contract)
    File.write(File.join(root, '.agents/trusted-github-actors.yml'), "users: []\n")
    write_probe(root)
    %w[setup validate test].each { |name| write_wrapper(root, name) }
  end

  def fixture_contract
    "version: 1\nreview:\n  required: none\nmerge:\n  preference: ask\n"
  end

  def write_probe(root)
    path = File.join(root, 'bin/probe')
    File.write(path, <<~SHELL)
      #!/bin/sh
      printf '%s\\n' "$PWD" "$@"
      [ "${1:-}" = fail ] && exit 23
      exit 0
    SHELL
    File.chmod(0o755, path)
  end

  def write_wrapper(root, name, source = nil)
    path = File.join(root, '.agents/bin', name)
    File.write(path, source || <<~SHELL)
      #!/bin/sh
      # Generated by shaka seam init.
      set -eu
      #{ROOT_LINE}
      cd "$root"
      exec "$root/bin/probe" "$@"
    SHELL
    File.chmod(0o755, path)
  end

  def commit_fixture(root, message = 'fixture')
    git!(root, 'init', '-q') unless File.exist?(File.join(root, '.git'))
    git!(root, 'add', '-A')
    git!(root, '-c', 'user.name=Test', '-c', 'user.email=test@example.com', 'commit', '-qm', message)
  end

  def upgrade(root, *)
    Open3.capture3(COMMAND, 'seam', 'upgrade', '--root', root, *)
  end

  def report(root, *)
    output, error, status = upgrade(root, *)
    assert_predicate status, :success?, error
    JSON.parse(output)
  end

  def apply_upgrade(root)
    report(root, '--apply', '--digest', report(root).fetch('digest'))
  end

  def git!(root, *)
    output, status = Open3.capture2e('git', '-C', root, *)
    raise output unless status.success?

    output
  end

  def write_journal(root, plan)
    original = plan.original_states
    journal = { 'version' => 1, 'original' => original, 'desired' => plan.desired_states,
                'digest' => plan.report.fetch('digest'),
                'temporary' => original.keys.map { |path| "#{path}.shaka-upgrade-tmp" },
                'created_directories' => ['.agents/shaka/bin', '.agents/shaka'] }
    File.write(Shaka::Seam::Upgrader.journal_path(root), JSON.generate(journal))
    journal
  end

  def plan_for(root)
    Shaka::Seam::UpgradePlan.new(root).tap(&:build)
  end

  def normalized_output(output)
    first, *rest = output.lines
    "#{File.realpath(first.strip)}\n#{rest.join}"
  end

  def assert_blocked_with(root, reason)
    preview = report(root)
    assert_equal 'blocked', preview.fetch('status')
    assert_includes preview.fetch('blockers').join, reason
  end
end
