# frozen_string_literal: true

require 'json'
require_relative '../error'
require_relative '../version'

module Shaka
  class Doctor
    # Reads the provenance generated by the managed installer, if present.
    class InstallationIdentity
      def self.read
        path = File.expand_path('../../../../../.shaka-install.json', __dir__)
        return uninstalled unless File.file?(path)

        identity = JSON.parse(File.read(path))
        raise Shaka::Error, 'Installed package metadata is invalid.' unless valid?(identity)

        identity
      rescue JSON::ParserError => e
        raise Shaka::Error, "Installed package metadata is invalid: #{e.message}"
      end

      def self.valid?(identity)
        return false unless identity.is_a?(Hash) && identity['version'].is_a?(String)

        source = identity['source']
        source.is_a?(Hash) && %w[revision development].include?(source['kind']) &&
          source['content_sha256'].is_a?(String) &&
          (source['kind'] != 'revision' || source['revision'].is_a?(String))
      end

      def self.uninstalled
        { 'schema_version' => 1, 'package_id' => nil, 'version' => Shaka::VERSION,
          'source' => { 'kind' => 'uninstalled', 'repository' => nil, 'revision' => nil,
                        'base_revision' => nil, 'content_sha256' => nil } }
      end

      private_class_method :valid?, :uninstalled
    end
  end
end
