# frozen_string_literal: true

require 'json'
require_relative '../error'
require_relative '../version'
require_relative '../install/package'

module Shaka
  class Doctor
    # Reads the provenance generated by the managed installer, if present.
    class InstallationIdentity
      def self.read
        path = File.expand_path('../../../../../.shaka-install.json', __dir__)
        return checkout_metadata(File.dirname(path)) unless File.file?(path)
        raise Shaka::Error, 'Installed package metadata is invalid.' if File.symlink?(path)

        identity = JSON.parse(File.read(path))
        raise Shaka::Error, 'Installed package metadata is invalid.' unless valid?(identity, path)

        identity
      rescue JSON::ParserError => e
        raise Shaka::Error, "Installed package metadata is invalid: #{e.message}"
      end

      def self.checkout_metadata(root)
        path = File.join(root, '.git', 'shaka-install.json')
        return missing_metadata(File.join(root, '.shaka-install.json')) unless File.file?(path)

        raise Shaka::Error, 'Installation record is invalid.' if File.symlink?(path)

        record = JSON.parse(File.read(path))
        identity = record['identity'] if record.is_a?(Hash)
        raise Shaka::Error, 'Installation record is invalid.' unless
          record.is_a?(Hash) && record['directory'] == File.realpath(root) && valid?(identity, path)

        identity
      end

      def self.missing_metadata(path)
        package = File.basename(File.dirname(path))
        raise Shaka::Error, 'Installed package metadata is missing.' if package.match?(Install::Package::ID_PATTERN)

        uninstalled
      end

      def self.valid?(identity, path)
        return false unless identity.is_a?(Hash) && identity['version'].is_a?(String)
        return false unless valid_source?(identity['source'])
        return false unless valid_skills?(identity['skills'])

        valid_package_id?(identity, path)
      end

      def self.valid_skills?(skills)
        Install::Package.valid_skills?(skills)
      end

      def self.valid_source?(source)
        source.is_a?(Hash) && %w[revision development].include?(source['kind']) &&
          source['content_sha256'].is_a?(String) &&
          (source['kind'] != 'revision' || source['revision'].is_a?(String))
      end

      def self.valid_package_id?(identity, path)
        package = File.basename(File.dirname(path))
        return true unless package.match?(Install::Package::ID_PATTERN)

        identity['package_id'] == package &&
          Install::Package.identity_for(identity['version'], identity['source']) == package
      end

      def self.uninstalled
        { 'schema_version' => 1, 'package_id' => nil, 'version' => Shaka::VERSION,
          'source' => { 'kind' => 'uninstalled', 'repository' => nil, 'revision' => nil,
                        'base_revision' => nil, 'content_sha256' => nil } }
      end

      private_class_method :valid?, :valid_source?, :valid_skills?, :valid_package_id?, :uninstalled,
                           :missing_metadata, :checkout_metadata
    end
  end
end
