# frozen_string_literal: true

require_relative '../version'

module Shaka
  class Seam
    # Explains the generated seam directory by pointing at the reference, not restating it.
    module InitializerReadme
      HOME = 'https://github.com/shakacode/shaka'
      DOCS = "#{HOME}/blob/main/docs".freeze
      LEGACY_README = '.agents/README.md'

      private

      def readme_source
        <<~MARKDOWN
          #{readme_marker}
          # Shaka configuration

          This repository uses Shaka #{Shaka::VERSION} (pilot stage #{Shaka::PRODUCT_STAGE})
          with contract `version: 1`. The files below hold its configuration.

          | Path | Purpose |
          | --- | --- |
          | `agent-workflow.yml` | Review, merge, and branch policy, read from the trusted default branch. Live GitHub settings still govern checks and approvals. |
          | `bin/` | Executable setup, test, and validation wrappers. Shaka runs the candidate checkout's copies; inspect changes before execution. |

          ## Check configuration edits

          `shaka seam check --root . --local`

          Validates the current checkout's YAML and scripts. Without `--ref`, it
          grants no trusted policy authority.

          ## Load trusted policy

          Resolve this repository's default branch to an immutable commit SHA, then:

          `shaka seam check --root . --ref SHA`

          A candidate PR cannot grant itself authority by changing its own policy.
          Copy-ready `AGENTS.md` guidance: `shaka seam pointer`.

          - [Configuration reference](#{DOCS}/settings.md) — every key, its type, and what it controls.
          - [Repository setup](#{DOCS}/agents/repository-setup.md) — how this directory was created.

          Generated by `#{generated_by}` from Shaka #{Shaka::VERSION}. Repeating that command
          leaves this file alone; it never overwrites one you have edited.
        MARKDOWN
      end

      def readme_marker = "<!-- Generated by #{generated_by}. -->"

      def generated_by = 'shaka seam init'

      def report_legacy_readme
        path = File.join(@root, LEGACY_README)
        return unless File.file?(path) && !File.symlink?(path)
        return unless legacy_generated_readme?(path)

        warn 'shaka: .agents/README.md is a legacy Shaka-generated pointer. Keep it, or ' \
             'copy useful notes into .agents/shaka.md; seam init will not delete it. ' \
             'A later explicit migration command may move it after ownership checks.'
      end

      def legacy_generated_readme?(path)
        File.read(path, encoding: 'UTF-8').start_with?(readme_marker)
      rescue Errno::EACCES, Errno::EPERM
        false
      end
    end
  end
end
