# frozen_string_literal: true

require 'yaml'
require_relative '../repository_config'
require_relative 'initializer_destination'
require_relative 'initializer_input'
require_relative 'initializer_readme'

module Shaka
  class Seam
    # Creates the smallest complete repository seam without replacing repo-owned files.
    class Initializer
      MARKER = 'Generated by shaka seam init.'
      POINTER_PATH = '.agents/shaka.md'
      COMMAND_NAMES = RepositoryConfig::CommandPaths::REQUIRED.keys.freeze

      include InitializerInput
      include InitializerDestination
      include InitializerReadme

      def initialize(root:, options:)
        @root = root
        @options = options
      end

      def call
        files = generated_files
        RepositoryConfig::ReviewSchema.new(review_policy).validate
        preflight_directories
        RepositoryConfig::CommandSchema.new(root: @root).validate_available_optional_commands
        preflight_files(files)
        write_files(files)
        report_legacy_readme
        RepositoryConfig.load(root: @root)
      end

      private

      def generated_files
        wrappers = COMMAND_NAMES.to_h do |name|
          command = required("#{name}_command").then { |value| command_arguments(value, name) }
          [File.join(@root, '.agents/bin', name), wrapper(command)]
        end
        wrappers.merge(File.join(@root, RepositoryConfig::PATH) => config_source,
                       File.join(@root, POINTER_PATH) => readme_source)
      end

      def config_source
        config = config_hash
        if @options[:plan]
          repository_file(@options[:plan], 'plan')
          config['plan'] = @options[:plan]
        end
        "# #{MARKER}\n#{YAML.dump(config)}"
      end

      # base_branch is omitted when it was not requested: an absent key means the
      # repository's default branch, so writing one would pin a value nobody chose.
      def config_hash
        {
          'version' => 1,
          'base_branch' => base_branch,
          'review' => review_policy,
          'merge' => { 'preference' => @options.fetch(:merge_preference, 'ask') },
          'branches' => { 'name' => '{login}-{host}/{issue}-{description}' }
        }.compact
      end

      def review_policy
        required_policy = required('review_policy')
        names = @options[:ci_review_agents]
        if required_policy == 'none'
          raise Error, '--ci-review-agent must be omitted when review policy is none' if names

          return { 'required' => required_policy }
        end
        raise Error, '--ci-review-agent is required' if names.nil? || names.empty?

        { 'required' => required_policy, RepositoryConfig::ReviewSchema::CI_REVIEW_AGENTS => names }
      end

      def wrapper(arguments)
        <<~SHELL
          #!/bin/sh
          # #{MARKER}
          set -eu
          root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
          cd "$root"
          exec #{arguments.shelljoin} "$@"
        SHELL
      end
    end
  end
end
