# frozen_string_literal: true

require 'fileutils'
require 'yaml'
require_relative '../repository_config'
require_relative 'initializer_input'

module Shaka
  class Seam
    # Creates the smallest complete repository seam without replacing repo-owned files.
    class Initializer
      MARKER = 'Generated by shaka seam init.'
      COMMAND_NAMES = %w[setup validate test].freeze

      include InitializerInput

      def initialize(root:, options:)
        @root = root
        @options = options
      end

      def call
        files = generated_files
        preflight_directories
        preflight_files(files)
        write_files(files)
        RepositoryConfig.load(root: @root)
      end

      private

      def generated_files
        wrappers = COMMAND_NAMES.to_h do |name|
          command = required("#{name}_command").then { |value| command_arguments(value, name) }
          [File.join(@root, '.agents/bin', name), wrapper(command)]
        end
        wrappers.merge(File.join(@root, RepositoryConfig::PATH) => config_source)
      end

      def config_source
        config = config_hash
        if @options[:plan]
          repository_file(@options[:plan], 'plan')
          config['plan'] = @options[:plan]
        end
        actions = string_list(:trusted_actions, 'trusted_action')
        config['trusted_actions'] = actions unless actions.empty?
        "# #{MARKER}\n#{YAML.dump(config)}"
      end

      def config_hash
        {
          'version' => 1,
          'base_branch' => base_branch,
          'commands' => COMMAND_NAMES.to_h { |name| [name, ".agents/bin/#{name}"] },
          'review' => review_policy,
          'merge' => merge_policy,
          'protection' => protection_policy
        }
      end

      def review_policy
        required_policy = required('review_policy')
        if required_policy == 'none'
          raise Error, '--review-check must be omitted when review policy is none' if @options.key?(:review_check)

          return { 'required' => required_policy }
        end

        { 'required' => required_policy, 'check' => required('review_check') }
      end

      def merge_policy
        { 'preference' => @options.fetch(:merge_preference, 'ask'),
          'method' => 'squash', 'release' => 'explicit_approval' }
      end

      def protection_policy
        { 'required_checks' => required_list(:required_checks, 'required_check'),
          'direct_push' => false, 'force_push' => false, 'branch_deletion' => false }
      end

      def wrapper(arguments)
        <<~SHELL
          #!/bin/sh
          # #{MARKER}
          set -eu
          root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
          cd "$root"
          exec #{arguments.shelljoin} "$@"
        SHELL
      end

      def preflight_directories
        ['.agents', '.agents/bin'].each do |relative|
          path = File.join(@root, relative)
          next unless File.exist?(path) || File.symlink?(path)

          raise Error, "Refusing unsafe directory: #{relative}" if File.symlink?(path) || !File.directory?(path)
        end
      end

      def preflight_files(files)
        files.each do |path, content|
          next unless File.exist?(path) || File.symlink?(path)
          next if File.file?(path) && !File.symlink?(path) && File.read(path, encoding: 'UTF-8') == content

          raise Error, "Refusing existing destination: #{path.delete_prefix("#{@root}/")}"
        end
      end

      def write_files(files)
        # Narrow accidental-change windows; same-target concurrent writers are unsupported.
        preflight_directories
        preflight_files(files)
        FileUtils.mkdir_p(File.join(@root, '.agents/bin'))
        preflight_directories
        files.each do |path, content|
          preflight_directories
          preflight_files(path => content)
          write_new_file(path, content) unless File.file?(path)
        end
      end

      def write_new_file(path, content)
        flags = File::WRONLY | File::CREAT | File::EXCL
        mode = File.dirname(path) == File.join(@root, '.agents/bin') ? 0o755 : 0o644
        File.open(path, flags, 0o600) do |file|
          file.write(content)
          file.chmod(mode)
        end
      end
    end
  end
end
