# frozen_string_literal: true

require_relative '../version'

module Shaka
  class Seam
    # Explains the generated seam directory by pointing at the reference, not restating it.
    module InitializerReadme
      HOME = 'https://github.com/shakacode/shaka'
      DOCS = "#{HOME}/blob/main/docs".freeze
      LEGACY_README = '.agents/README.md'

      private

      def readme_source
        <<~MARKDOWN
          #{readme_marker}
          # `.agents/shaka.md`

          Shaka skill #{Shaka::VERSION} (product stage #{Shaka::PRODUCT_STAGE}) owns this pointer.
          The seam contract is `version: 1`. This file is not repository policy.

          | Path | What it is |
          | --- | --- |
          | `agent-workflow.yml` | The typed contract for Shaka-specific workflow policy. Shaka reads it from the trusted default branch, so a pull request cannot grant itself authority by editing its own copy. Live GitHub settings remain authoritative. |
          | `bin/` | Standard wrappers for this repository's setup, validation, and tests. Their fixed names form the portable command interface; they run from the checkout under review, so a pull request that edits one changes what validation executes. |

          ## Candidate / local validation (grants no authority)

          `shaka seam check --root . --local`

          Validates the current checkout's YAML and scripts. Without `--ref`, it
          grants no trusted policy authority.

          ## Trusted policy loading

          Resolve this repository's default branch to an immutable commit SHA, then:

          `shaka seam check --root . --ref SHA`

          That command is fail-closed: omit `--ref` and it cannot load trusted policy.
          Copy-ready `AGENTS.md` guidance: `shaka seam pointer`.

          - [Seam settings](#{DOCS}/settings.md) — every key, its type, and what it controls.
          - [Getting started](#{DOCS}/getting-started.md#initialize-a-repository-seam) — how this directory was created.

          Generated by `#{generated_by}` from Shaka #{Shaka::VERSION}. Repeating that command
          leaves this file alone; it never overwrites one you have edited.
        MARKDOWN
      end

      def readme_marker = "<!-- #{Initializer::MARKER} -->"

      def generated_by = 'shaka seam init'

      def report_legacy_readme
        path = File.join(@root, LEGACY_README)
        return unless File.file?(path) && !File.symlink?(path)
        return unless legacy_generated_readme?(path)

        warn 'shaka: .agents/README.md is a legacy Shaka-generated pointer. Keep it, or ' \
             'copy useful notes into .agents/shaka.md; seam init will not delete it. ' \
             'A later explicit migration command may move it after ownership checks.'
      end

      def legacy_generated_readme?(path)
        File.read(path, encoding: 'UTF-8').start_with?(readme_marker)
      rescue Errno::EACCES, Errno::EPERM
        false
      end
    end
  end
end
