# frozen_string_literal: true

require 'yaml'
require_relative '../configuration'
require_relative 'initializer_destination'
require_relative 'initializer_input'
require_relative 'initializer_readme'

module Shaka
  class Seam
    # Creates the smallest complete repository seam without replacing repo-owned files.
    class Initializer
      MARKER = 'Generated by shaka seam init.'
      POINTER_PATH = Configuration::Paths::POINTER
      COMMAND_NAMES = Configuration::Paths::REQUIRED_COMMANDS.keys.freeze

      include InitializerInput
      include InitializerDestination
      include InitializerReadme

      def initialize(root:, options:)
        @root = root
        @options = options
      end

      def call
        files = generated_files
        RepositoryConfig::ReviewSchema.new(review_policy).validate
        RepositoryConfig::MergeSchema.new(merge_policy).validate
        preflight_directories
        refuse_new_configuration!
        RepositoryConfig::CommandSchema.new(root: @root).validate_available_optional_commands
        preflight_files(files)
        write_files(files)
        report_legacy_readme
        Configuration.worktree(root: @root)
      end

      private

      def refuse_new_configuration!
        return unless Configuration::Layout.worktree(root: @root, allow_missing: true) == Configuration::Layout::NEW

        raise Error, "#{Configuration::Paths::NEW_CONTRACT} already exists; seam init writes " \
                     "#{Configuration::Paths::CONTRACT} and cannot create a second configuration"
      end

      def generated_files
        wrappers = COMMAND_NAMES.to_h do |name|
          command = required("#{name}_command").then { |value| command_arguments(value, name) }
          [Configuration.command_path(@root, name), wrapper(command)]
        end
        wrappers.merge(Configuration.path(@root, :CONTRACT) => config_source,
                       Configuration.path(@root, :POINTER) => readme_source)
      end

      def config_source
        config = config_hash
        Configuration.generated_contract(marker: MARKER, data: config)
      end

      # base_branch is omitted when it was not requested: an absent key means the
      # repository's default branch, so writing one would pin a value nobody chose.
      def config_hash
        {
          'version' => 1,
          'base_branch' => base_branch,
          'review' => review_policy,
          'merge' => merge_policy,
          'branches' => { 'name' => '{login}-{host}/{issue}-{description}' }
        }.compact
      end

      def merge_policy
        { 'preference' => @options.fetch(:merge_preference, 'ask'),
          RepositoryConfig::MergeSchema::REQUIRED_CHECKS => @options[:required_checks] }.compact
      end

      def review_policy
        required_policy = required('review_policy')
        names = @options[:ci_review_jobs]
        if required_policy == 'none'
          raise Error, '--ci-review-job must be omitted when review policy is none' if names

          return { 'required' => required_policy }
        end
        raise Error, '--ci-review-job is required' if names.nil? || names.empty?

        { 'required' => required_policy, RepositoryConfig::ReviewSchema::CI_REVIEW_JOBS => names }
      end

      def wrapper(arguments)
        <<~SHELL
          #!/bin/sh
          # #{MARKER}
          set -eu
          root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
          cd "$root"
          exec #{arguments.shelljoin} "$@"
        SHELL
      end
    end
  end
end
