# frozen_string_literal: true

require_relative '../version'

module Shaka
  class Seam
    # Explains the generated seam directory by pointing at the reference, not restating it.
    module InitializerReadme
      HOME = 'https://github.com/shakacode/shaka'
      DOCS = "#{HOME}/blob/main/docs".freeze

      private

      def readme_source
        <<~MARKDOWN
          #{readme_marker}
          # `.agents`

          This directory is this repository's contract with the [Shaka](#{HOME}) workflow.

          | Path | What it is |
          | --- | --- |
          | `agent-workflow.yml` | The typed contract: commands, review, merge, and branch-protection policy. Shaka reads it from the trusted default branch, so a pull request cannot grant itself authority by editing its own copy. |
          | `bin/` | Wrappers for this repository's own setup, validate, and test commands. The contract only names them; they run from the checkout under review, so a pull request that edits one changes what validation executes. |

          Edit `agent-workflow.yml` by hand, then validate it with `shaka seam check --root .`.
          Validation is strict: unknown keys, unsafe paths, and missing or non-executable
          scripts fail rather than being ignored. Keep human-only constraints in `AGENTS.md`;
          this directory holds only typed policy.

          - [Seam settings](#{DOCS}/settings.md) — every key, its type, and what it controls.
          - [Getting started](#{DOCS}/getting-started.md#initialize-a-repository-seam) — how this directory was created.

          Generated by `shaka seam init` from Shaka #{Shaka::VERSION}. Repeating that command
          leaves this file alone; it never overwrites one you have edited.
        MARKDOWN
      end

      def readme_marker = "<!-- #{Initializer::MARKER} -->"
    end
  end
end
