# frozen_string_literal: true

require 'open3'
require_relative '../error'
require_relative '../configuration'
require_relative 'check_report'
require_relative 'migration_apply'
require_relative 'migration_plan'
require_relative 'migrator_parser'

module Shaka
  class Seam
    # Plans a typed-seam migration from an immutable predecessor ref; apply is explicit.
    class Migrator
      include MigratorParser
      include MigrationPlan
      include MigrationApply

      MARKER = 'Generated by shaka seam migrate.'
      CONTRACT = Configuration::Paths::CONTRACT

      def self.run(arguments)
        arguments = arguments.dup
        arguments.shift if arguments.first == 'migrate'
        new(arguments).run
      rescue OptionParser::ParseError, SystemCallError, Shaka::Error => e
        warn "shaka: #{e.message}"
        1
      end

      def initialize(arguments)
        @arguments = arguments
        @options = {}
      end

      def run
        parse!
        return 0 if @options[:help]

        load_predecessor!
        report = build_report
        return apply(report) if @options[:apply]

        CheckReport.emit(report)
      end

      private

      def root = @root ||= File.realpath(@options.fetch(:root))

      def load_predecessor!
        @sha = Configuration.resolve_commit(root:, ref: @options.fetch(:from_ref), label: 'from-ref')
        @source, @data = Configuration.predecessor(root:, sha: @sha, ref: @options[:from_ref])
      end
    end
  end
end
