# frozen_string_literal: true

require 'open3'
require 'yaml'
require_relative '../error'
require_relative '../repository_config'
require_relative '../repository_config/duplicate_keys'
require_relative 'check_report'
require_relative 'migration_apply'
require_relative 'migration_plan'
require_relative 'migrator_parser'

module Shaka
  class Seam
    # Plans a typed-seam migration from an immutable predecessor ref; apply is explicit.
    class Migrator
      include MigratorParser
      include MigrationPlan
      include MigrationApply

      MARKER = 'Generated by shaka seam migrate.'
      CONTRACT = RepositoryConfig::PATH

      def self.run(arguments)
        arguments = arguments.dup
        arguments.shift if arguments.first == 'migrate'
        new(arguments).run
      rescue OptionParser::ParseError, SystemCallError, Shaka::Error => e
        warn "shaka: #{e.message}"
        1
      end

      def initialize(arguments)
        @arguments = arguments
        @options = {}
      end

      def run
        parse!
        return 0 if @options[:help]

        load_predecessor!
        report = build_report
        return apply(report) if @options[:apply]

        CheckReport.emit(report)
      end

      private

      def root = @root ||= File.realpath(@options.fetch(:root))

      def load_predecessor!
        @sha = resolve(@options.fetch(:from_ref))
        @source, error, status = Open3.capture3('git', '-C', root, 'show', "#{@sha}:#{CONTRACT}")
        raise Error, "Cannot read #{CONTRACT} at #{@options[:from_ref]}: #{error.strip}" unless status.success?

        RepositoryConfig::DuplicateKeys.check(@source, filename: CONTRACT)
        @data = YAML.safe_load(@source, permitted_classes: [], permitted_symbols: [], aliases: false)
      rescue Psych::Exception => e
        raise Error, "Invalid #{CONTRACT}: #{e.message}"
      end

      def resolve(ref)
        sha, error, status = Open3.capture3('git', '-C', root, 'rev-parse', '--verify', '--end-of-options',
                                            "#{ref}^{commit}")
        raise Error, "Invalid from-ref #{ref}: #{error.strip}" unless status.success?

        sha.strip
      end
    end
  end
end
